Vagrant.configure("2") do |config|

    config.vm.define "cent7" do |cent_config|
        cent_config.vm.box = "centos/7"
        cent_config.vm.network "private_network", ip: "192.168.50.11"
        cent_config.vm.provision "shell", inline: <<-SHELL
              sudo rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
              sudo yum install -y puppet
        SHELL
        cent_config.vm.provision "shell", path: "manifests/init_puppet.sh"
    end

    ## Mostra gui do virtualbox, define memoria e cpu.
    config.vm.provider :virtualbox do |vb|
        vb.gui = true
        vb.memory = 2024
        vb.cpus = 1
    end
end
